export const GET_GNOMES = 'GET_GNOMES';
export const GET_GNOMES_SUCCESFULLY = 'GET_GNOMES_SUCCESFULLY'
export const GET_GNOMES_ERROR ='GET_GNOMES_ERROR'



export const GET_GNOME_FILTER_NAME = 'GET_GNOME_FILTER_NAME'
export const GET_GNOME_FILTER_ERROR = 'GET_GNOME_FILTER_ERROR'