export const GET_GNOMES = 'GET_GNOMES';
export const GET_GNOMES_SUCCESFULLY = 'GET_GNOMES_SUCCESFULLY'
export const GET_GNOMES_ERROR ='GET_GNOMES_ERROR'

export const GET_GNOME_FILTER = 'GET_GNOME_FILTER'
export const GET_GNOME_FILTER_SUCCESFULLY = 'GET_GNOME_FILTER_SUCCESFULLY'
export const GET_GNOME_FILTER_ERROR = 'GET_GNOME_FILTER_ERROR'